### ISSUE TITLE
from exceptions import failes

### ISSUE THREAD

**Issue by chrisallick** [ckreutzer/python-tvrage#1] opened 2011-12-06 02:29 UTC
all tests pass except for the exceptions because the import doesn't work.  I replaced the from and just imported exceptions to run the test api.  great library, thanks.

chrisallick:tvrage chrisallick$ ls
**init**.py     api.py          api.pyc         api_tests.py        exceptions.py       feeds.py        feeds.pyc       quickinfo.py        quickinfo_test.py   util.py         util.pyc
chrisallick:tvrage chrisallick$ python api_tests.py 
Traceback (most recent call last):
  File "api_tests.py", line 33, in <module>
    from api import Show
  File "/Users/chrisallick/Downloads/tvrage/api.py", line 35, in <module>
    from exceptions import (ShowHasEnded, FinaleMayNotBeAnnouncedYet,
ImportError: cannot import name ShowHasEnded
chrisallick:tvrage chrisallick$ python
Python 2.6.1 (r261:67515, Jun 24 2010, 21:47:49) 
[GCC 4.2.1 (Apple Inc. build 5646)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import exceptions
> > > ^D
> > > chrisallick:tvrage chrisallick$

**Comment by ckreutzer** [comment] 2012-09-16 09:38
Hi, the issue is fixed by now. Sorry for my late answer... perhaps you want to check out last nights v0.4.0.

**Closed as completed by ckreutzer** 2012-09-16 09:38 UTC
